const connections = [
	["SA", "NF", 2, "At the top of the stair, turn left onto the station catwalk", "../assets/sample_image.jpg"],
	["SB", "NF", 2, "At the top of the stair, turn right onto the station catwalk", "../assets/sample_image.jpg"],
	["SC", "NG", 2, "At the top of the escalator, turn right onto the station catwalk", "../assets/sample_image.jpg"],
	["SD", "NG", 2, "At the top of the escalator, turn left onto the station catwalk", "../assets/sample_image.jpg"],
	["SE", "NH", 2, "When leaving the elevator walk to the left down the station catwalk", "../assets/sample_image2.jpg"],
	["SE", "NK", 2, "When leaving the elevator walk to the right down the station catwalk", "../assets/sample_image.jpg"],
	["SF", "NH", 2, "When leaving the elevator walk to the right down the station catwalk", "../assets/sample_image.jpg"],
	["SF", "NK", 2, "When leaving the elevator walk to the left down the station catwalk", "../assets/sample_image.jpg"],
	["SG", "NN", 2, "When leaving the escalator walk out to the middle of the station catwalk", "../assets/sample_image.jpg"],
	["SH", "NN", 2, "When leaving the escalator walk out to the middle of the station catwalk", "../assets/sample_image.jpg"],
	["SI", "NO", 2, "When leaving the escalator walk out to the middle of the station catwalk", "../assets/sample_image.jpg"],
	["SJ", "NO", 2, "When leaving the escalator walk out to the middle of the station catwalk", "../assets/sample_image.jpg"],
	["NA", "NB", 3, "Turn right and walk around the outside of the station", "../assets/sample_image.jpg"],
	["NA", "NC", 3, "Turn left and walk around the outside of the station", "../assets/sample_image.jpg"],
	["NA", "NV", 2, "Walk straight toward all the restaurants and stores", "../assets/sample_image.jpg"],
	["NA", "NF", 3, "N/A", "../assets/sample_image.jpg"],
	["NB", "NA", 3, "N/A", "../assets/sample_image.jpg"],
	["NB", "NE", 5, "Walk towards the Woolworths entrance", "../assets/sample_image.jpg"],
	["NC", "NA", 3, "N/A", "../assets/sample_image.jpg"],
	["NC", "ND", 3, "Walk around the outside, past the information screens", "../assets/sample_image.jpg"],
	["ND", "NC", 3, "N/A", "../assets/sample_image.jpg"],
	["ND", "EL", 2, "On your right there is a staircase. Start walking up them.", "../assets/sample_image.jpg"],
	["ND", "NJ", 9, "Continue straight down the outside of the station", "../assets/sample_image.jpg"],
	["NE", "NB", 5, "N/A", "../assets/sample_image.jpg"],
	["NE", "EA", 2, "To the left of the Woolworths entrance, take the staircase", "../assets/sample_image.jpg"],
	["NE", "NI", 5, "Continue straight down the outside of the station", "../assets/sample_image.jpg"],
	["NF", "NA", 3, "Walk towards the stores and restaurants then through the station gates", "../assets/sample_image.jpg"],
	["NF", "SA", 2, "N/A", "../assets/sample_image.jpg"],
	["NF", "NG", 4, "Walk away from the stores and restaurant towards the middle of the station", "../assets/sample_image.jpg"],
	["NF", "SB", 2, "N/A", "../assets/sample_image.jpg"],
	["NG", "NF", 4, "Walk up the station catwalk towards QVB", "../assets/sample_image.jpg"],
	["NG", "SC", 2, "N/A", "../assets/sample_image.jpg"],
	["NG", "NH", 4, "Walk down the catwalk towards the middle of the station", "../assets/sample_image.jpg"],
	["NG", "SD", 2, "N/A", "../assets/sample_image.jpg"],
	["NH", "NG", 4, "Walk up the station catwalk towards the gates on the very end", "../assets/sample_image.jpg"],
	["NH", "NJ", 3, "Go through the gates on the side towards St Andrews Cathedral", "../assets/sample_image.jpg"],
	["NH", "SE", 2, "N/A", "../assets/sample_image.jpg"],
	["NH", "NK", 3, "Walk down the catwalk between the elevators", "../assets/sample_image.jpg"],
	["NH", "SF", 2, "N/A", "../assets/sample_image.jpg"],
	["NH", "NI", 3, "Go through the gates on the side towards the Station Office", "../assets/sample_image.jpg"],
	["NI", "NE", 5, "Walk up the outside of the station towards the entrance of the Woolworths", "../assets/sample_image.jpg"],
	["NI", "NH", 3, "N/A", "../assets/sample_image.jpg"],
	["NI", "NM", 3, "Walk down the outside of the station towards the end of the station", "../assets/sample_image.jpg"],
	["NI", "EB", 2, "To the left of the Station Office entrance, go up the staircase", "../assets/sample_image.jpg"],
	["NJ", "ND", 9, "Walk up the outside of the station towards the big scrolling information screens", "../assets/sample_image.jpg"],
	["NJ", "NT", 3, "Walk through the tunnel towards Town Hall Plaza Darling Harbour", "../assets/sample_image.jpg"],
	["NJ", "NL", 3, "Walk down the outside of the station towards the far end near Bathurst Street", "../assets/sample_image.jpg"],
	["NJ", "NH", 3, "N/A", "../assets/sample_image.jpg"],
	["NK", "NH", 3, "Walk up the station catwalk towards the middle of the station", "../assets/sample_image.jpg"],
	["NK", "SE", 2, "N/A", "../assets/sample_image.jpg"],
	["NK", "NL", 3, "Go through the gates on the side towards St Andrews Cathedral", "../assets/sample_image.jpg"],
	["NK", "NN", 3, "Walk down the station catwalk towards the end of the station", "../assets/sample_image.jpg"],
	["NK", "NM", 3, "Go through the gates on the side towards Station Office", "../assets/sample_image.jpg"],
	["NK", "SF", 2, "N/A", "../assets/sample_image.jpg"],
	["NL", "NJ", 3, "Walk up the outside towards the tunnel on the side of the station", "../assets/sample_image.jpg"],
	["NL", "NR", 8, "Walk down the outside toward the end of the station near Bathurst Street", "../assets/sample_image.jpg"],
	["NL", "NK", 3, "N/A", "../assets/sample_image.jpg"],
	["NM", "NI", 3, "Walk up the outside of the station toward the Station Office against the wall"],
	["NM", "NK", 3, "N/A", "../assets/sample_image.jpg"],
	["NM", "NS", 4, "Walk down the outside of the station towards the Town Hall Pavilion Plaza", "../assets/sample_image.jpg"],
	["NN", "NK", 3, "Walk up the catwalk towards the middle of the station", "../assets/sample_image.jpg"],
	["NN", "SG", 2, "N/A", "../assets/sample_image.jpg"],
	["NN", "NO", 4, "Walk down the catwalk towards the Town Hall Pavilion Plaza", "../assets/sample_image.jpg"],
	["NN", "SH", 2, "N/A", "../assets/sample_image.jpg"],
	["NO", "NN", 4, "Walk up the catwalk towards the centre of the station", "../assets/sample_image.jpg"],
	["NO", "SI", 2, "N/A", "../assets/sample_image.jpg"],
	["NO", "NP", 3, "Walk through the gates at the end of the station", "../assets/sample_image.jpg"],
	["NO", "SJ", 2, "N/A", "../assets/sample_image.jpg"],
	["NP", "NO", 3, "N/A", "../assets/sample_image.jpg"],
	["NP", "NR", 4, "Turn right and walk around the corner along the outside of the station.", "../assets/sample_image.jpg"],
	["NP", "NQ", 3, "Turn left towards the Pavilion Plaza entrance.", "../assets/sample_image.jpg"],
	["NQ", "NS", 5, "Walk up the outside of the station towards the other end.", "../assets/sample_image.jpg"],
	["NQ", "NP", 3, "Walk to the gates on the end of the station catwalk", "../assets/sample_image.jpg"],
	["NQ", "EF", 2, "Walk through the tunnel to Pavilion Plaza and there will be several openings", "../assets/sample_image.jpg"],
	["NR", "NL", 8, "Walk up the outside of the station towards the other end", "../assets/sample_image.jpg"],
	["NR", "EG", 2, "There will be a staircase on the outside wall you can walk up", "../assets/sample_image.jpg"],
	["NR", "NP", 4, "Walk around the corner around the outside of the station", "../assets/sample_image.jpg"],
	["NS", "NM", 4, "Walk up the outside of the station towards the Station Office", "../assets/sample_image.jpg"],
	["NS", "NQ", 5, "Walk down the outside of the station towards the opening to get to Pavilion Plaza", "../assets/sample_image.jpg"],
	["NS", "ED", 2, "Against the wall there is an elevator. Call the elevator and get inside.", "../assets/sample_image.jpg"],
	["NS", "EC", 2, "Opposite the elevator there will be a staircase to walk up", "../assets/sample_image.jpg"],
	["NT", "EI", 2, "Walk up the staircase on the right side of the tunnel", "../assets/sample_image.jpg"],
	["NT", "NU", 9, "Walk through the tunnel to the split in the path", "../assets/sample_image.jpg"],
	["NT", "EH", 2, "Walk up the staircase on the left side of the tunnel", "../assets/sample_image.jpg"],
	["NT", "NJ", 3, "N/A", "../assets/sample_image.jpg"],
	["NU", "NT", 9, "N/A", "../assets/sample_image.jpg"],
	["NU", "EJ", 5, "Turn right at the split towards Darling Harbour via Druitt Street", "../assets/sample_image.jpg"],
	["NU", "EK", 9, "Turn left at the split towards Darling Harbour via Bathurst Street", "../assets/sample_image.jpg"],
	["NV", "NW", 5, "Turn right at the split towards The Galeries", "../assets/sample_image.jpg"],
	["NV", "NX", 7, "Turn left at the split towards Queen Victoria Building", "../assets/sample_image.jpg"],
	["NV", "NA", 2, "N/A", "../assets/sample_image.jpg"],
	["NW", "NV", 5, "N/A", "../assets/sample_image.jpg"],
	["NW", "EM", 2, "As you're walking past all the stores, you will see a staircase on the right", "../assets/sample_image.jpg"],
	["NX", "NV", 7, "N/A", "../assets/sample_image.jpg"],
	["NX", "EN", 2, "You will see a staircase on the left to walk up.", "../assets/sample_image.jpg"],
	["EA", "NN", 2, "N/A", "../assets/sample_image.jpg"],
	["EB", "NI", 2, "N/A", "../assets/sample_image.jpg"],
	["EC", "NS", 2, "N/A", "../assets/sample_image.jpg"],
	["ED", "NS", 2, "N/A", "../assets/sample_image.jpg"],
	["EF", "NQ", 2, "N/A", "../assets/sample_image.jpg"],
	["EG", "NR", 2, "N/A", "../assets/sample_image.jpg"],
	["EH", "NT", 2, "N/A", "../assets/sample_image.jpg"],
	["EI", "NT", 2, "N/A", "../assets/sample_image.jpg"],
	["EJ", "NU", 9, "N/A", "../assets/sample_image.jpg"],
	["EK", "NU", 5, "N/A", "../assets/sample_image.jpg"],
	["EL", "ND", 2, "N/A", "../assets/sample_image.jpg"],
	["EM", "NW", 2, "N/A", "../assets/sample_image.jpg"],
	["EN", "NX", 2, "N/A", "../assets/sample_image.jpg"],
]

export function getDescFromNodes(currNode, nextNode) {
	let desc = "";
	connections.map((connection) => {
		if(connection[0] == currNode && connection[1] == nextNode){
			desc = connection[3];
		}
	});
	return desc;
}

export default connections;