const connections = [
	["SA", "NF", 2, "1-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SB", "NF", 2, "2-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SC", "NG", 2, "3-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SD", "NG", 2, "4-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SE", "NH", 2, "5-No description has been provided for this step", "../assets/sample_image2.jpg"],
	["SE", "NK", 2, "6-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SF", "NH", 2, "7-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SF", "NK", 2, "8-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SG", "NN", 2, "9-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SH", "NN", 2, "10-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SI", "NO", 2, "11-No description has been provided for this step", "../assets/sample_image.jpg"],
	["SJ", "NO", 2, "12-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NA", "NB", 3, "13-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NA", "NC", 3, "14-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NA", "NV", 2, "15-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NA", "NF", 3, "16-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NB", "NA", 3, "17-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NB", "NE", 5, "18-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NC", "NA", 3, "19-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NC", "ND", 3, "20-No description has been provided for this step", "../assets/sample_image.jpg"],
	["ND", "NC", 3, "21-No description has been provided for this step", "../assets/sample_image.jpg"],
	["ND", "EL", 2, "22-No description has been provided for this step", "../assets/sample_image.jpg"],
	["ND", "NJ", 9, "23-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NE", "NB", 5, "24-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NE", "EA", 2, "25-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NE", "NI", 5, "26-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NF", "NA", 3, "27-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NF", "SA", 2, "28-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NF", "NG", 4, "29-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NF", "SB", 2, "30-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NG", "NF", 4, "31-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NG", "SC", 2, "32-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NG", "NH", 4, "33-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NG", "SD", 2, "34-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NH", "NG", 4, "35-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NH", "NJ", 3, "36-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NH", "SE", 2, "37-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NH", "NK", 3, "38-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NH", "SF", 2, "39-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NH", "NI", 3, "40-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NI", "NE", 5, "41-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NI", "NH", 3, "42-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NI", "NM", 3, "43-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NI", "EB", 2, "44-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NJ", "ND", 9, "45-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NJ", "NT", 3, "46-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NJ", "NL", 3, "47-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NJ", "NH", 3, "48-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NK", "NH", 3, "49-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NK", "SE", 2, "50-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NK", "NL", 3, "51-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NK", "NN", 3, "52-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NK", "NM", 3, "53-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NK", "SF", 2, "54-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NL", "NJ", 3, "55-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NL", "NR", 8, "56-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NL", "NK", 3, "57-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NM", "NI", 3, "58-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NM", "NK", 3, "59-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NM", "NS", 4, "60-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NN", "NK", 3, "61-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NN", "SG", 2, "62-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NN", "NO", 4, "63-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NN", "SH", 2, "64-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NO", "NN", 4, "65-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NO", "SI", 2, "66-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NO", "NP", 3, "67-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NO", "SJ", 2, "68-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NP", "NO", 3, "69-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NP", "NR", 4, "70-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NP", "NQ", 3, "71-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NQ", "NS", 5, "72-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NQ", "NP", 3, "73-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NQ", "EF", 2, "74-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NR", "NL", 8, "75-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NR", "EG", 2, "76-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NR", "NP", 4, "77-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NS", "NM", 4, "78-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NS", "NQ", 5, "79-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NS", "ED", 2, "80-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NS", "EC", 2, "81-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NT", "EI", 2, "82-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NT", "NU", 9, "83-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NT", "EH", 2, "84-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NT", "NJ", 3, "85-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NU", "NT", 9, "86-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NU", "EJ", 5, "87-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NU", "EK", 9, "88-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NV", "NW", 5, "89-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NV", "NX", 7, "90-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NV", "NA", 2, "91-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NW", "NV", 5, "92-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NW", "EM", 2, "93-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NX", "NV", 7, "94-No description has been provided for this step", "../assets/sample_image.jpg"],
	["NX", "EN", 2, "95-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EA", "NN", 2, "96-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EB", "NI", 2, "97-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EC", "NS", 2, "98-No description has been provided for this step", "../assets/sample_image.jpg"],
	["ED", "NS", 2, "99-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EF", "NQ", 2, "100-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EG", "NR", 2, "101-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EH", "NT", 2, "102-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EI", "NT", 2, "103-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EJ", "NU", 9, "104-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EK", "NU", 5, "105-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EL", "ND", 2, "106-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EM", "NW", 2, "107-No description has been provided for this step", "../assets/sample_image.jpg"],
	["EN", "NX", 2, "108-No description has been provided for this step", "../assets/sample_image.jpg"],
]

export function getDescFromNodes(currNode, nextNode) {
	let desc = "";
	connections.map((connection) => {
		if(connection[0] == currNode && connection[1] == nextNode){
			desc = connection[3];
		}
	});
	return desc;
}

export default connections;