const graph = {
    NA: { NV: 2, NC: 3, NB: 3, NF: 3 },
    NB: { NA: 3, NE: 5 },
    NC: { NA: 3, ND: 3 },
    ND: { EL: 2, NJ: 9 },
    NE: { NB: 5, EA: 2 },
    NF: { NA: 3, SA: 2, SB: 2, NG: 4 },
    NG: { NF: 4, SC: 2, SD: 2, NH: 4 },
    NH: { NG: 4, NJ: 3, NI: 3, SE: 2, SF: 2, NK: 3 },
    NI: { NE: 5, EB: 2, NH: 3, NM: 3 },
    NJ: { ND: 9, NH: 3, NT: 2, NL: 3 },
    NK: { NL: 3, SE: 2, SF: 2, NH: 3, NM: 3, NN: 3 },
    NL: { NJ: 3, NK: 3, NR: 8 },
    NM: { NI: 3, NK: 3, NS: 3 },
    NN: { SG: 2, NK: 3, SH: 2, NO: 4 },
    NO: { NN: 4, SI: 2, SJ: 2, NP: 3 },
    NP: { NO: 3, NR: 4, NQ: 3 },
    NQ: { NS: 5, NP: 3, EF: 2 },
    NR: { EG: 2, NP: 4, NL: 8 },
    NS: { NM: 4, NQ: 5, EC: 2, ED: 2 },
    NT: { NJ: 2, EI: 2, EH: 2, NU: 9 },
    NU: { NT: 9, EJ: 5, EK: 9 },
    NV: { NA: 2, NW: 5, NX: 7 },
    NW: { NV: 5, EM: 2 },
    NX: { NV: 7, EN: 2 },
    EA: { NE: 2 },
    EB: { NI: 2 },
    EC: { NS: 2 },
    ED: { NS: 2 },
    EF: { NQ: 2 },
    EG: { NR: 2 },
    EH: { NT: 2 },
    EI: { NT: 2 },
    EJ: { NU: 5 },
    EK: { NU: 9 },
    EL: { ND: 2 },
    EM: { NW: 2 },
    EN: { NX: 2 },
    SA: { NF: 2 },
    SB: { NF: 2 },
    SC: { NG: 2 },
    SD: { NG: 2 },
    SE: { NH: 2, NK: 2 },
    SF: { NH: 2, NK: 2 },
    SG: { NN: 2 },
    SH: { NN: 2 },
    SI: { NO: 2 },
    SJ: { NO: 2 },
  };

  export default graph;